// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cranepurple700': string;
  'cranepurple800': string;
  'cranepurple900': string;
  'cranered400': string;
  'opacity': string;
  'purple': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
