export declare type optionTypes = {
  amLabel?: string;
  animation?: boolean;
  appendModalSelector?: string;
  backdrop?: boolean;
  cancelLabel?: string;
  editable?: boolean;
  enableScrollbar?: boolean;
  enableSwitchIcon?: boolean;
  mobileTimeLabel?: string;
  focusInputAfterCloseModal?: boolean;
  hourMobileLabel?: string;
  iconTemplate?: string;
  iconTemplateMobile?: string;
  incrementHours?: number;
  incrementMinutes?: number;
  minuteMobileLabel?: string;
  mobile?: boolean;
  okLabel?: string;
  pmLabel?: string;
  preventDefault?: boolean;
  timeLabel?: string;
  switchToMinutesAfterSelectHour?: boolean;
  theme?: 'basic' | 'crane-straight' | 'crane-radius';
  clockType?: '12h' | '24h';
  disabledTime?: any;
};
